### ISSUE TITLE
How can I upload image with base64 data on S3?

### ISSUE THREAD

**Issue by bdavid68** [jb55/s3-blob-store#15]
I am going to upload an image on S3 with base64 data. But I am not sure how to do it and get url of uploaded image.
I would be appreciate if you can help me.
Thank you!

**Comment by jb55** [comment]
Consider asking your question on https://stackoverflow.com/, this issue tracker is for issues related to s3-blob-store. Sorry!

Hint: You'll need to decode the base64 data and then write it to the s3-blob-store's write stream.
