### ISSUE TITLE
Support range requests

### ISSUE THREAD

**Issue by olalonde** [jb55/s3-blob-store#4]
Would be nice if createReadStream would support HTTP Range requests.

**Comment by jb55** [comment]
This might be better in an S3 [chunk-store](https://github.com/mafintosh/abstract-chunk-store), although there might be some uses cases for streaming sections of a file...

**Comment by olalonde** [comment]
FWIW, I temporarily adapted this module to support range requests but had to get rid of the custom downloader: https://github.com/olalonde/s3-simple-blob-store

**Comment by jb55** [comment]
Why not pull request? That looks much simpler than the current implementation

**Comment by jb55** [comment]
This will be a nice complement to #5 as well, so we can get rid of both dependencies and just use the aws-sdk

**Comment by olalonde** [comment]
Oh sorry, I was under the impression you wanted to keep that dependency. I can send a PR in that case.

**Comment by olalonde** [comment]
Sent PR: https://github.com/jb55/s3-blob-store/pull/6

FWIW, I've also sent a PR to fs-blob-store to support the same interface: https://github.com/mafintosh/fs-blob-store/pull/2

**Comment by olalonde** [comment]
Any chance to get support for range requests?

**Comment by jb55** [comment]
Yeah sorry I think I'm going to keep this as a strict abstract-blob-store and nothing else.
